### ISSUE TITLE
Specify LICENSE

### ISSUE THREAD

**Issue by Freso** [DelusionalLogic/skymod#1]
There's currently no license, so the terms of redistribution etc. are unclear. I would recommend one of the licenses given at https://opensource.org/licenses - but you may also look to e.g., LOOT, Mod Organizer, Nexus Mod Manager, Mator's projects, etc. depending on your plans if you want/need to be compatible with any of their licenses (e.g., to be able to copy code freely).

**Comment by DelusionalLogic** [comment]
You're right. I'll add the GPL license when I get around to it.

Suffice it to say that for all intents and purposes it's released as GPL right now.

**Comment by DelusionalLogic** [comment]
I went ahead and added the license and headers.
